language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - DEPENDENCIES=lowest
  - DEPENDENCIES=highest

before_script:
  - composer self-update
  - composer global require hirak/prestissimo
  - if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;

script:
  - vendor/bin/phing build-ci
