language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - DEPENDENCIES=lowest
  - DEPENDENCIES=highest

cache:
    directories:
        - ~/.composer/cache

before_script:
  - echo "xdebug.max_nesting_level=1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer global require hirak/prestissimo
  - if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;

script:
  - vendor/bin/phing build-ci
